// <auto-generated />
namespace ImageTagging.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Multitag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Multitag));
        
        string IMigrationMetadata.Id
        {
            get { return "201705260655163_Multitag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
